spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  security:
    oauth2:
      client:
        registration:
          # google:
            # client-id: <client-id>
            # client-secret: <client-secret>
            # scope:
            #   - email
            #   - openid
            #   - profile
          okta:
            client-id: <client-id>
            client-secret: <client-secret>
        provider:
          okta:
            authorization-uri: https://{uri}/oauth2/default/v1/authorize
            token-uri: https://{uri}/oauth2/default/v1/token
            user-info-uri: https://{uri}/oauth2/default/v1/userinfo
            jwk-set-uri: https://{uri}/oauth2/default/v1/keys
            issuer-uri: https://{uri}/oauth2/default

          google:
            issuer-uri: https://accounts.google.com
            user-name-attribute: email

okta:
  oauth2:
    issuer: https://{uri}/oauth2/default
    clientId: <client-id>
    clientSecret: <client-secret>
    audience: api://default
    groupsClaim: <group-name>
